dracut-module-setup.sh

There is a bug report for RHEL10 about a grep error reading
grep: /var/tmp/dracut.DiZuKp/initramfs/etc/systemd/system.conf*: No such file or directory
that shows up when rebuilding the initrd. This is caused by systemd v255 that allows installing the default systemd config files to /usr/lib/systemd instead of /etc/systemd [1][2] which is done for RHEL. So unless a user manually adds /etc/systemd/system.conf the file no longer exists.
However the test that requires the call to grep is somewhat wonky. IIUC the test is there so we don't overwrite a setting the user might have made. In my opinion this only makes sense as long as the timeout set is larger than what we would set. But this part of the logic is missing. So fix the error message by removing the test and add our config …

dracut-module-setup: Fix missing systemd/system.conf error

---

dracut-module-setup.sh

This PR fixes three cases where network dumping fails,
- PHY drive is missing
- MDIO bus driver is missing
- a NIC is a Single Root I/O Virtualization (SR-IOV) virtual device

Install PHY and MDIO bus drivers and  the driver of physical device for a SR-IOV virtual device

---

98-kexec.rules
98-kexec.rules.ppc64

In kernel, with the support of cpu/memory hotplug on crash, kdump reloading only needs to update the elfcorehdr.
To realize the benefits, we need prevent udev from updating kdump kernel on hot un/plug changes when detecting that the crash_hotplug sysfs nodes are present.
Link: https://lore.kernel.org/lkml/20230814214446.6659-1-eric.devolder@oracle.com/
Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d68b4b6f307d155475cce541f2aee938032ed22e

update 98-kexec rules for crash hotplug

---

gen-kdump-sysconfig.sh

There have been some of failing cases of kdump in 2nd kernel, where ususally only one cpu is enabled by "nr_cpus=1", but with a large number of devices, which may easily exceed the maximum IRQ resources of one cpu can handle. As a result, the 2nd kernel will hang and kdump fails. This issue is often observed on machines with many cpus and many devices.
On those systems, pcieports consume quite proportion of IRQ resources, many following message can be seen in dmesg log:
pcieport 0000:18:01.0: PME: Signaling with IRQ 109
According to kernel doc[1], when "pcie_ports=compat" applied, it will disable native PCIe services (PME, AER, DPC, PCIe hotplug). Those functions are power management events, error reporting, performance, hotplug related, which are not the must-have functions for kdump. In …

[PATCH v2] sysconfig: add pcie_ports compat to KDUMP_COMMANDLINE_APPEND on x86_64

---

98-kexec.rules.ppc64

With the introduction of kernel commit c6c5b14dac0d ("powerpc: make fadump resilient with memory add/remove events") linux kernel now internally manages the update of elfcorehdr during memory add/remove events. So no need to re-register fadump if the /sys/kernel/fadump/hotplug_ready is set to 1.
No impact for kernels that do not have /sys/kernel/fadump/hotplug_ready sysfs.
Relevant kernel commit links:
1. https://msgid.link/20240422195932.1583833-2-sourabhjain@linux.ibm.com
2. https://msgid.link/20240422195932.1583833-3-sourabhjain@linux.ibm.com

fadump/udev: do not re-register fadump if kernel hotplug ready

---

dracut-module-setup.sh

Use "grep -q <<< $(cmd)" instead of "cmd | grep -q"
The following line of code's exit value should be the exit value of
grep by default:
cmd | grep -q
However it will not always work as expected, a 141 exit code may be
returned, see the following debug info:
--- a/usr/lib/dracut/modules.d/99kdumpbase/module-setup.sh
+++ b/usr/lib/dracut/modules.d/99kdumpbase/module-setup.sh
@@ -55,6 +55,11 @@ depends() {
_dep="$_dep ssh-client"
fi
+    dracut --list-modules 1>&2
+    echo $? 1>&2
+    dracut --list-modules | grep -q lvmthinpool-monitor
+    echo $? ${PIPESTATUS[0]} ${PIPESTATUS[1]} 1>&2
+
if is_lvm2_thinp_dump_target; then
if dracut --list-modules | grep -q lvmthinpool-monitor; then
add_opt_module lvmthinpool-monitor
$ kdumpctl rebuild
kdump: Rebuilding …

Use "grep -q <<< $(cmd)" instead of "cmd | grep -q"

---

kdumpctl
kexec-kdump-howto.txt

This series removes the -d option set per default to kexec followed by some small cleanup patches. Please see the patch description for details

Remove default debug option

---

Makefile
dracut-kdump.sh
gen-kdump-sysconfig.sh
kdump-lib.sh
kdumpctl
kdumpctl.8

During the last test cycle and the following discussion several issues were found. This series fixes most of them.
Note: The last commit of the series depends on PR #12. Unfortunately I couldn't find a way to tell GitHub this connection. Thus this PR also contains the identical commit to the one from PR #12.
Depends on PR #12

Various fixes

---

kdump.service

Using Privatetmp=yes will cause mountinfo changes, which will cause kdump started via systemd to fail in scenarios using bind mount such as coreos. Temporarily disable it until the bind mount problem is resolved.
Fixes: ea00b7db("kdumpctl: Move temp file in get_kernel_size to global temp dir")

Temporary disable PrivateTmp=yes

---

dracut-module-setup.sh

Resolves: https://issues.redhat.com/browse/RHEL-33465
This patch supports setting up an Ovs bridge in kdump initrd. An Ovs
bridge is similar to a classic Linux bridge but we use ovs-vsctl to find
out the Ethernet device (having the MAC address as the bridge) added to
an Ovs bridge. Once we copy all the needed NetworkManager (NM) connection
profiles to kdump initrd and all the necessary files, NM will create an Ovs bridge
automatically in kdump initrd.
In the case of OpenShift Container Platform (OCP),
ovs-configuration.service [1] is responsible for setting up an Ovs bridge.
In theory, we can also try to bring up the original physical network
interface before ovs-configuration.service. But this approach is
cumbersome because it breaks our assumption that we should bring up the
same …

Support setting up Openvswitch (Ovs) Bridge network

---

mkdumprd

Resolves: https://issues.redhat.com/browse/RHEL-57006
05rdma dracut module from rdma-core is installed unconditionally even if kdump dumps the vmcore to local disk. And those kmod will cost additional 200M memory on x86, which likely triggers OOM.
Since the Infiniband (and in fact none of RDMA devices are supported in kdump), exclude the rdma dracut module explicitly.

mkdumprd: Omit rdma module

---

dracut/99kdumpbase/kdump.sh
dracut/99kdumpbase/module-setup.sh
gen-kdump-sysconfig.sh
kdump-lib-initramfs.sh
kdumpctl
kdumpctl.8
mkdumprd

Introduce vmcore creation notification to kdump
Motivation
==========
People may forget to recheck to ensure kdump works, which as a result, a
possibility of no vmcores generated after a real system crash. It is
unexpected for kdump.
It is highly recommended people to recheck kdump after any system
modification, such as:
a. after kernel patching or whole yum update, as it might break something
on which kdump is dependent, maybe due to introduction of any new bug etc.
b. after any change at hardware level, maybe storage, networking,
firmware upgrading etc.
c. after implementing any new application, like which involves 3rd party modules
etc.
Though these exceed the range of kdump, however a simple vmcore creation
status notification is good to have for now.
Design
======
Kdump currently …

Introduce vmcore creation notification to kdump

---

kdump-lib-initramfs.sh
kdump-lib.sh
spec/kdump-lib-initramfs_spec.sh

We use findmnt to find the real mount point by mount source, however, when there is a bind mount target, findmnt will give more than one results and what we actually want is the one without fsroot.
Will fallback to previous method if the $_mntpoint is empty.

kdump-lib-initramfs: Improve mount point retrieval logic

---

dracut/99kdumpbase/module-setup.sh

Since #41 has already been merged into main, let's merge this commit from #28 and then close it.

dracut: Disable ostree-prepare-root

---

kdump.service

Commit 0084806493d0 ("kdump.service: use ConditionKernelCommandLine=crashkernel") added a condition based on the crashkernel kernel command line parameter to control the start of the kdump service.
While ConditionKernelCommandLine=crashkernel works well for kdump, it causes issues for fadump (specific to the PowerPC architecture), which also uses the same service unit. Unlike kdump, crashkernel kernel command-line is not mandatory for fadump.
Since ConditionKernelCommandLine doesn't support evaluating multiple kernel command line parameters with dependencies between them, it has been replaced with ExecCondition to resolve this limitation.
Now, if fadump is configured and the crashkernel parameter is NOT present in the kernel command line, kdump service will start.
Fixes: #35

kdump.service: Replace ConditionKernelCommandLine with ExecCondition

---

kdumpctl

Resolves: https://issues.redhat.com/browse/RHEL-63047
The exit code of rebuild_initrd() should be either of
rebuild_kdump/fadump_initrd(), rather than set_vmcore_creation_status(),
otherwise it will cause a regression when rebuild initrd fails.
Fixes: 88525ebf ("Introduce vmcore creation notification to kdump")
Signed-off-by: Tao Liu <ltao@redhat.com>

Return the correct exit code of rebuild initrd

---

crashkernel-howto.txt
kdumpctl
kdumpctl.8

The --reboot option for reset-crashkernel causes quite some confusion. Especially, there are different expectations when --reboot shall reboot the system. The current code only reboots the system when the crashkernel parameter was updated during this run. But there are other opinions, that --reboot shall also reboot the system if a previous run of `kdumpctl reset-crashkernel` updated the crashkernel parameter and no reboot occurred yet. While possible this would add extra complexity to the code. Neither the confusion nor the extra complexity are justified, given that --reboot only replaces a single additional command for the user.
Thus deprecate the --reboot option so it can be removed later on.

kdumpctl: deprecate --reboot for reset-creashkernel

---

fadump-howto.txt
gen-kdump-sysconfig.sh
kdump-lib.sh
kdumpctl

Since kernel commit 3416c9daa6b13 ("powerpc/fadump: pass additional parameters when fadump is active"), fadump supports passing additional parameters to dump capture kernel. Leverage that support here to pass additional parameters to dump capture kernel.
Also, update fadump-howto.txt to make clear on the options that are not relevant for fadump in /etc/sysconfig/kdump
The default bootargs to append for fadump capture kernel boot are chosen with the intent to optimize resources and reduce memory footprint in dump capture environment.

fadump: pass additional parameters for capture kernel

---

kdumpctl

Currently, additional parameters for fadump capture kernel are being set only with reload command. In fact, the check for bootargs_append node before writing to it is incorrect too. Fix it and also, setup fadump aditional parameters for start/restart case as well.
Fixes: 77b80ce5 ("fadump: pass additional parameters for capture kernel")

fadump: fix passing additional parameters for capture kernel

---

99-kdump.conf
Makefile
mkdumprd

In some cases, we need to change dracut [omit_]dracutmodules to customize the first kernel's initrd to meet the needs, such as bootc and CoreOS.
In most cases kdump does not use these modules, but the change of [omit]_dracutmodules may break existing functionality. For example, if we set omit_dracutmodules='nfs', the nfs module cannot be added even if we use "dracut_args --force-add 'nfs'".
It is better to maintain its own dracut config for kdump. As the first try, we start by keeping [omit_]dracutmodules empty.
As a side effect, the default confdir "/etc/dracut.conf.d" will not work while generating kdump initrd.
And dracut can only use --confdir once, so "dracut_args --confidr" in /etc/kdump.conf will no longer work. This may be avoided in the future by adding something like …

Add kdump dracut config

---

kdump-utils.spec

Resolves: https://github.com/rhkdump/kdump-utils/issues/56
Currently, kdump-utils fails to upgrade to
kdump-utils-1.0.48-1.fc42.ppc64le on ppc64le FCOS as servicelog_notify failed to be executed,
... rpm-ostree(kdump-utils.post)[2376]: + touch /etc/kdump.conf
... rpm-ostree(kdump-utils.post)[2376]: + servicelog_notify --remove --command=/usr/lib/kdump/kdump-migrate-action.sh
... rpm-ostree(kdump-utils.post)[2376]: + servicelog_notify --add --command=/usr/lib/kdump/kdump-migrate-action.sh '--match=refcode="#MIGRATE" and serviceable=0' --type=EVENT --method=pairs_stdin
... rpm-ostree(kdump-utils.post)[2382]: No such file or directory
RPM scriplets should always return 0 status code to avoid breaking installs/upgrades/erases [1].
[1] …

Let %post scriptlet always exit successfully

---

dracut/99kdumpbase/kdump.sh
gen-kdump-sysconfig.sh
kdump-lib-initramfs.sh
kdumpctl
kdumpctl.8
mkdumprd

Motivation
==========
People may forget to recheck to ensure kdump works, which as a result, a
possibility of no vmcores generated after a real system crash. It is
unexpected for kdump.
It is highly recommended people to test kdump after any system modification,
such as:
a. after kernel patching or whole yum update, as it might break something
on which kdump is dependent, maybe due to introduction of any new bug etc.
b. after any change at hardware level, maybe storage, networking,
firmware upgrading etc.
c. after implementing any new application, like which involves 3rd party modules
etc.
Though these exceed the range of kdump, however a simple vmcore creation
status notification is good to have for now.
Design
======
Kdump currently will check any relating files/fs/drivers modified …

Re-introduce vmcore creation notification to kdump

---

kdumpctl

This PR fixes a small bug introduced with the `kdumpctl test` rewrite. As well as some ShellCheck findings introduced with recent features.

kdumpctl/test: fix fetching of status for ssh targets with IPv6

---

gen-kdump-conf.sh

Resolves: https://issues.redhat.com/browse/RHEL-69568
Suggested-by: Ryosuke Yasuoka <ryasuoka@redhat.com>

Note user-specified crashkernel value will be overwritten by default value

---

.cci.jenkinsfile

This will uses Fedora CoreOS jenkins instance to run tests on PRs for this repo. It simply uses packit to create an RPM and build an FCOS VM image with it, then run some kdump tests. 
Example of a run : https://jenkins-coreos-ci.apps.ocp.fedoraproject.org/blue/organizations/jenkins/kdump-upstream/detail/enable-coreos-ci/5/pipeline
Here are the tests being run : 
- [local dump](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/tests/kola/kdump/crash/test.sh)
- [over SSH](https://github.com/coreos/coreos-assembler/blob/17c1cc8ea2463a111074c06bb916fcfbfd0964ba/mantle/kola/tests/ignition/kdump.go#L120)
- [over NFS](https://github.com/coreos/coreos-assembler/pull/3922). Note this one is not active, waiting on dracut 104.
Note that you need to be a members of `coreos` or …

CI: build coreOS with kdump RPM and run tests

---

dracut/99kdumpbase/module-setup.sh

Resolves: https://issues.redhat.com/browse/RHEL-67131
Some drivers like dwmac_tegra may report its name incorrectly. So fallback to /sys/class/net/NIC/device/driver/modul to address these cases. Note this method only for physical NICs i.e it doesn't work for virtual NICs like bonding NIC.
Suggested-by: Michal Schmidt <mschmidt@redhat.com>

Fallback to get NIC driver by /sys/class/net/NIC/device/driver/module

---

tests/setup/lvm2_thinp/test.sh

Somehow LVM2-thinp test fails occasionally. It turns out the test fails
because /etc/lvm/devices/system.devices somehow becomes empty file after
a kernel panic,
[root@client ~]# journalctl -b0 |grep vdb
Aug 02 08:10:52 localhost kernel: virtio_blk virtio2: [vdb] 2097152 512-byte logical blocks (1.07 GB/1.00 GiB)
Aug 02 08:10:54 client lvm[712]: /dev/vdb excluded by devices file (checking PVID).
[root@client ~]# cat /etc/lvm/devices/system.devices
[root@client ~]# pvscan -vvv
/dev/vdb: Skipping (deviceid)
"sync -f /etc/lvm/devices/system.devices" doesn't work for this case. So
simply delete it to prevent an empty /etc/lvm/devices/system.devices. An
empty system.devices will filter out the LVM device (dev/vdb) [1].
Note the failure of this flaky test can happen 1/15 times,
log_dir=logs_dir …

tests: fix occasional LVM2-thinp test failures

---

98-kexec.rules.ppc64

Sysfs /sys/kernel/fadump/hotplug_ready contains 1 if hotplug is supported by fadump.
Now to exit early the RUN command should grep 0 from /sys/kernel/fadump/hotplug_ready instead of 1.
Fix it by updating RUN command.
Fixes: b4e3d3724cf3 ("fadump/udev: do not re-register fadump if kernel hotplug ready")

powerpc: fix early exit from udev on hotplug event for fadump

---

99-kdump.conf

Resolves: https://issues.redhat.com/browse/RHEL-52304
The nouveau module provides no significant utility in second kernel, and it introduces firmware that occupies approximately 38MB of memory, which is critical in the constrained environment of kdump. Omit it helps reduce memory usage and optimize the crash recovery process.

99-kdump.conf: Omit nouveau module

---

tests/plans/main.fmf

By default, the embedded task essential-requires runs before all prepare tasks,
queued prepare task #1: essential-requires on client and server
queued prepare task #2: Set root password on client and server
queued prepare task #3: Use custom mirror on client and server
queued prepare task #4: Install built RPM on client
And it takes 13m to finish the SSH dumping tests. By running task "Use custom mirror" early, the test could be finished within 3m.

tests: set up custom mirror before essential-requires

---

mkdumprd

Resolves: https://issues.redhat.com/browse/RHEL-75539
A proposal [1] has been submitted to remove fips-mode-setup from Fedora
42. And we are suggested to tell if FIPS has been enabled by check if /proc/sys/crypto/fips_enabled has 1.
[1] https://fedoraproject.org/wiki/Changes/RemoveFipsModeSetup#Feedback
[2] https://developers.redhat.com/articles/2024/02/27/handling-fips-mode-upstream-projects-rhel#

Check /proc/sys/crypto/fips_enabled to tell if FIPS has been enabled

---

.github/workflows/main.yml
tests/plans/local.fmf
tests/plans/nfs.fmf
tests/plans/nfs_early.fmf
tests/plans/ssh.fmf
tests/tests/check_vmcore/test.sh
tools/run-integration-tests.sh

Resolves: https://issues.redhat.com/browse/KEX-203
By running kdump-utils tests against Fedora rawhide, we can catch regressions earlier. This will also cover latest dracut as kdump heavily depends on dracut.

Enable tests against rawhide

---

crashkernel-howto.txt
kdump-lib.sh

With new kernel features being added, both the kernel itself and the initramfs have gradually increased in size.
Previously, we used squashfs to package and reduce the initramfs size. However, since squashfs will be replaced by erofs, we have transitioned to erofs. The compression algorithms supported by erofs differ from those used in squashfs. In previous squashfs implementations, we used zstd compression, but in RHEL-10, the erofs implementation in the kernel does not yet support zstd decompression. As a result, we had to switch to other compression algorithms, leading to changes in the initramfs size.
In some scenarios, the previous 192M crashkernel reservation is no longer sufficient. Recent NFS testing has shown that at least 238M is required to successfully capture a vmcore. Given …

kdump-lib.sh: Adjust default crashkernel reservation for x86_64 and s390x

---

kdump-lib.sh
spec/kdump-lib_spec.sh

The kernel code to calculate reserving size rounded up the total_mem because
usually the memblock usable mem size is smaller than the physical dimm memory
size:
total_mem = roundup(total_mem, SZ_128M);
This patch is aimed to align with the kernel's behavior. A machine showing
4000MB of total memory will be treated as having 4G instead of 3G memory.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2306493
Signed-off-by: Lichen Liu <lichliu@redhat.com>

kdump-lib.sh: rounded up the total_mem to 128M in get_system_size

---

99-kdump.conf

The clevis related dracut modules are unconditionly included into the kdump initramfs after installing clevis-dracut package.
Normally, we don't use clevis in the kdump process, but it will increase the size of kdump initramfs by about 11M, which is a relatively large overhead for kdump. Omit them by default can reduce the memory required by kdump and avoid the OOM issue.
If the user really needs to use it, it can also be added to kdump initramfs by using dracut_args --force-add in /etc/kdump.conf.
Resolves: https://issues.redhat.com/browse/RHEL-19064
Related: https://issues.redhat.com/browse/RHEL-77112

99-kdump.conf: Omit clevis related dracut modules

---

dracut/99kdumpbase/module-setup.sh
tests/plans/main.fmf
tests/plans/nfs_ovs.fmf
tests/setup/ovs_network/main.fmf
tests/setup/ovs_network/test.sh

Resolves: https://issues.redhat.com/browse/RHEL-75547
Currently, kdump tries to bring up the same network as in 1st kernel as
we assume if the same network works in the 1st kernel, there is no
reason it won't work in 1st kernel.
But for Open vSwitch (OVS) bridge, there are two challenges,
1. Extra memory requirement
For example, crashkernel=260M will be needed for OVS bridge while
only crashkernel=192M is sufficient for default network for F40 cloud
image.
2. A bit complex dependencies
An extra dracut module is needed to install dependent executables,
helper scripts, configuration files and a NetworkManager plugin.
To avoid the above challenges, we try to bring up the network before OVS
bridge instead. OVS bridge is set up by ovs-configuration.service
[1][2], we can assume the previous …

Bring up the network before Open vSwitch bridge

---

dracut/99kdumpbase/module-setup.sh
supported-kdump-targets.txt

The dracut nvmf module can take care of all things. It can parse ACPI
NVMe Boot Firmware Table (NBFT) tables, generate NetworkManager profiles
and discover and connect all subsystems.
Currently, the dracut kdump module will try to bring up the same network
connections as in 1st kernel. But a different set of NVMe connections
and active network interfaces will be used for the case of multipathing.
So the dracut kdump module should let dracut nvmf module do everything.
Note connecting everything and having network redundancy may require extra
memory and the default crashkernel may not work. We'll document this
issue and ask users to increase the crashkernel.

Support dumping to NVMe/TCP configured using NVMe Boot Firmware Table

---

60-kdump.install

When multiple BLS types exist on the system, do not remove kdump initrd.
See https://github.com/systemd/systemd/pull/37897

60-kdump.install: Skip removing initrd when multiple BLS types exist

---

.github/workflows/main.yml
dracut/99kdumpbase/kexec-crypt-setup.sh
dracut/99kdumpbase/module-setup.sh
kdump-lib-initramfs.sh
kdump-lib.sh
kdump-udev-throttler
kdumpctl
mkdumprd
supported-kdump-targets.txt

LUKS is the standard for Linux disk encryption. Many users choose LUKS
and in some use cases like Confidential VM it's mandated. With kdump
enabled, when the 1st kernel crashes, the system could boot into the
kdump/crash kernel and dump the memory image i.e. /proc/vmcore to a
specified target. Currently, when dumping vmcore to a LUKS
encrypted device, there are two problems,
- Kdump kernel may not be able to decrypt the LUKS partition. For some
machines, a system administrator may not have a chance to enter the
password to decrypt the device in kdump initramfs after the 1st kernel
crashes; For cloud confidential VMs, depending on the policy the
kdump kernel may not be able to unseal the keys with TPM and the
console virtual keyboard is untrusted.
- LUKS2 by default use the memory-hard …

kdump LUKS support

---

dracut/99kdumpbase/kexec-crypt-setup.sh
dracut/99kdumpbase/module-setup.sh
kdump-lib-initramfs.sh
kdump-lib.sh
kdumpctl
kdumpctl.8
kexec-kdump-howto.txt
spec/kdumpctl_setup_crypttab_spec.sh
supported-kdump-targets.txt

Resolves: https://issues.redhat.com/browse/RHEL-29037
Relates: https://issues.redhat.com/browse/RHEL-29039
This subcommand is to add the 'link-volume-key' option to /etc/crypttab
so the volume keys can be passed to the crash kernel to unlock
LUKS-encrypted device automatically.
This API will be also be called by kdump-anaconda-addon to set up
/etc/crypttab on installation.
Signed-off-by: Coiby Xu <coxu@redhat.com>

Add kdumpctl setup-crypttab subcommand
